### ISSUE TITLE
Error while global search. There is not null check

### ISSUE THREAD

**Issue by parvezdesignworks** [AlexanderKrutov/DataTables.Queryable#12]
Hi

This is truly a wonderful lib.

I am unable to resolve a **big issue** that is if the value is null there is a search error,

Before this 
`Expression.Call(propertyExp, Object_ToString);`

**there should be an null check** 

and later instead of this
`Expression.Lambda<Func<T, bool>>(containsMethodExp, parameterExp);`

Something like this
```
var andExp = Expression.And(nullChk, containsMethodExp);
return Expression.Lambda<Func<T, bool>>(andExp, parameterExp);
```

Needed help to do a null chk expression,
Scratching head from 2 days.

**Comment by parvezdesignworks** [comment]
SOLVED

comment this line in QueryableExtensions.cs and write the below code
//return Expression.Lambda<Func<T, bool>>(containsMethodExp, parameterExp);

var Equal_MI = typeof(object).GetMethod("Equals", new[] { propertyExp.Type, typeof(object) });
var left = Expression.Convert(propertyExp, typeof(object));
var right = Expression.Constant(null);
var nullExp = Expression.Call(null, Equal_MI, left, right);
var conditionExp = Expression.Condition(nullExp, Expression.Constant(false), containsMethodExp);
return Expression.Lambda<Func<T, bool>>(conditionExp, parameterExp);

**Comment by AlexanderKrutov** [comment]
@parvezdesignworks thank you for the bug report and sorry for the late response.
Null check can be added even shortly:
```cs
var notNullExp = Expression.NotEqual(exp, Expression.Constant(null, typeof(object)));
return Expression.Lambda<Func<T, bool>>(Expression.AndAlso(notNullExp, containsMethodExp), parameterExp);
```
Done in 1.6.2 version.
