### ISSUE TITLE
Can we get a version that targets the new netstandard2.0?

### ISSUE THREAD

**Issue by VictorioBerra** [AlexanderKrutov/DataTables.Queryable#15]

**Comment by sebastianbk** [comment]
When is this coming? It can't be too hard to do?

**Comment by VictorioBerra** [comment]
It was super easy I did it here at work but I can't share the code. Just create a new dotnet core 2. 1 his files and don't forget to add ef core

Also there might be a fork that somebody already did it. Check the forks of this project

**Comment by sebastianbk** [comment]
Hi @VictorioBerra. Thanks for the tip. I followed your advice and created this: https://github.com/sebastianbk/DataTables.Queryable.Core

**Comment by sebastianbk** [comment]
Hi again. Thanks a lot for the tips. It seems like you have spent quite a lot of time figuring out the best way to handle the interaction between DataTable and ASP.NET. 😃 I think I will stick with this library for now but, if I run into any of the issues you mention, I will definitely have a look at your links. Cheers!

**Comment by AlexanderKrutov** [comment]
Latest versions (since 1.7.0) of the library support .Net Core 2.0. Please check the: https://www.nuget.org/packages/DataTables.Queryable
