### ISSUE TITLE
Pulling these straight from the request instead of accepting a DTO?

### ISSUE THREAD

**Issue by VictorioBerra** [AlexanderKrutov/DataTables.Queryable#16]
It would be nice to accept the following maybe in addition to using the request in its "raw" form. The main reason for this is that Swashbuckle cannot tell swagger about the parameter. Also I think this would allow for better overriding and custom logic and stuff.

```csharp
public class DataTableAjaxPostModel
{
    public int draw { get; set; }
    public int start { get; set; }
    public int length { get; set; }
    public List<Column> columns { get; set; }
    public Search search { get; set; }
    public List<Order> order { get; set; }
}
 
public class Column
{
    public string data { get; set; }
    public string name { get; set; }
    public bool searchable { get; set; }
    public bool orderable { get; set; }
    public Search search { get; set; }
}
 
public class Search
{
    public string value { get; set; }
    public string regex { get; set; }
}
 
public class Order
{
    public int column { get; set; }
    public string dir { get; set; }
}
```

> Taken from: https://datatables.net/forums/discussion/40690/sample-implementation-of-serverside-processing-in-c-mvc-ef-with-paging-sorting-searching

**Comment by AlexanderKrutov** [comment]
Hi @VictorioBerra,
if I correctly understand the question, the main idea is to have type-parameterless `DataTablesRequest` class, because in some cases type `T` is not known at compile time. Is it right?

**Comment by VictorioBerra** [comment]
Right. It would be nice for a constructor overload in `DataTablesRequest.cs` to take the above `DataTableAjaxPostModel`. This way the model binder for web API works. And also so tools like swagger can document what parameters are acceptable to the endpoint.

**Comment by AlexanderKrutov** [comment]
@VictorioBerra Thank you for the pull request! I slightly refactored your code (see [commit](https://github.com/AlexanderKrutov/DataTables.Queryable/commit/cde75d8b4d833d755ad855f781ad8187a1de37c5)) and going to include AJAX POST model support to the new version of the library. So I have to close your original pull.

**Comment by VictorioBerra** [comment]
Looks great.
