### ISSUE TITLE
NullReferenceException inside GetPropertyByName

### ISSUE THREAD

**Issue by VictorioBerra** [AlexanderKrutov/DataTables.Queryable#34]
https://github.com/AlexanderKrutov/DataTables.Queryable/blob/master/DataTables.Queryable/DataTablesRequest.cs#L254

The bug is here `type.GetProperty(parts[0]).PropertyType`. `GetProperty` returns null, so this will explode and is never caught. Obviously this was hard to catch because it only happens when you are accessing a nested property.

**Comment by AlexanderKrutov** [comment]
Thank you! The fix is included in 1.7.2.

**Comment by VictorioBerra** [comment]
@AlexanderKrutov You are a good man. Thanks for being so quick on these.
