### ISSUE TITLE
Support for Multiple Filter Values on Same Column

### ISSUE THREAD

**Issue by nchelix** [AlexanderKrutov/DataTables.Queryable#37]
DataTables allows a regex search joining values on "|" to filter on a column for multiple values. 

Documented here:
https://datatables.net/forums/discussion/6946/multiple-filters-on-same-column

Currently, the ability to join search criteria with a "|" does not produce the expected results.

**Comment by AlexanderKrutov** [comment]
@nchelix As previously mentioned by @VictorioBerra, server-side regex search is not supported. I recommend to use `GlobalSearchPredicate` or `CustomFilterPredicate` (depend on your needs), see [Sample2](https://github.com/AlexanderKrutov/DataTables.Queryable/blob/817be59fbe7d66313709b5d374fd49c84705478f/DataTables.Queryable.Samples/Controllers/DataTablesController.cs#L40) and [Sample3](https://github.com/AlexanderKrutov/DataTables.Queryable/blob/817be59fbe7d66313709b5d374fd49c84705478f/DataTables.Queryable.Samples/Controllers/DataTablesController.cs#L63).
