### ISSUE TITLE
How to use with Razor Pages

### ISSUE THREAD

**Issue by arc95** [AlexanderKrutov/DataTables.Queryable#46]
Hi. Great library! Can it be used with Core Razor Pages? Any example? Thanks.

**Comment by VictorioBerra** [comment]
You can just look at the sample controller for different options. For example, you could handle a POST like this: https://github.com/AlexanderKrutov/DataTables.Queryable/blob/master/DataTables.Queryable.Samples/Controllers/DataTablesController.cs#L89

**Comment by arc95** [comment]
Thank you, @VictorioBerra. Your help is much appreciated.
