### ISSUE TITLE
Column with no data

### ISSUE THREAD

**Issue by dedo1911** [AlexanderKrutov/DataTables.Queryable#9]
I'm trying to render a column with no data coming from Database.
Currently I had to set columDefs data AND name to null, then modified DataTablesRequest.cs at row 174 I skip the exception if propertyName is null and both data and name are empty.

Is there an easier way to skip table association for fields without modifying the code, or you want me to pull request this little change.

**Comment by AlexanderKrutov** [comment]
Hi @dedo1911,
unfortunately it's not easy to understand the idea of the fix because the pull request contains a lot of changes related to refactoring.
Could you please separate it into 2 pull requests, first one for the proposed fix/solution, and second one is for refactoring only. Thanks!
